
jobs:
  - name: nginx-manifest
    type: manifest
    steps:
      - IN: nginx-image-1
      - IN: nginx-image-2
      # - IN: rsync_test_gitRepo
      #   showBuildStatus: true

  - name: sample-runCLI
    type: runCLI
    steps:
      - IN: rsync_test_gitRepo
        showBuildStatus: true
      - IN: rsync_test_gitRepo2
        showBuildStatus: true
      - TASK:
        - script: printenv
        - script: echo 'ec29ss'

  # - name: sample-runCLI
  #   type: runCLI
  #   steps:
  #     - IN: rsync_test_gitRepo
  #       showBuildStatus: true
  #     - TASK:
  #       - script: printenv
  #       - script: echo 'ec29ss'



  # - name: sample-runSh
  #   type: runSh
  #   steps:
  #     - IN: rsync_test_gitRepo
  #     - TASK:
  #       - script: printenv

  # - name: ci-jacoco_runCI
  #   type: runCI
  #   steps:
  #     - OUT: nginx-image-1
      # - TASK:
      #   - script: printenv
      #   - script: echo 'hello123'
