
jobs:
  - name: nginx-manifest
    type: manifest
    steps:
      - IN: nginx-image-1
      - IN: nginx-image-2
      - IN: rsync_test_gitRepo

  - name: sample-runSh
    type: runSh
    steps:
      - IN: rsync_test_gitRepo
      - TASK:
        - script: printenv

  # - name: sample-runSh
  #   type: runSh
  #   steps:
  #     - IN: rsync_test_gitRepo
  #     - TASK:
  #       - script: printenv
  #       - script: echo 'ec298777'

  # - name: ci-jacoco_runCI
  #   type: runCI
  #   steps:
  #     - OUT: nginx-image-1
      # - TASK:
      #   - script: printenv
      #   - script: echo 'hello123'